# Generated by Django 2.2.6 on 2019-11-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='idrfid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
