# Generated by Django 2.2.1 on 2019-10-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroRFID', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='fecha',
        ),
    ]
