# Generated by Django 2.2.6 on 2019-11-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroRFID', '0002_remove_registro_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='prueba',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
