# Generated by Django 2.2.6 on 2019-11-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroRFID', '0003_registro_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='prueba',
        ),
        migrations.AddField(
            model_name='registro',
            name='codigo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
