# Generated by Django 2.2.6 on 2019-11-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroRFID', '0004_auto_20191104_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='codigo',
        ),
        migrations.AddField(
            model_name='registro',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
