# Generated by Django 2.2.6 on 2019-11-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroRFID', '0005_auto_20191104_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='status',
        ),
        migrations.AddField(
            model_name='registro',
            name='nombre',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
