# Generated by Django 2.2.6 on 2019-11-04 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registroRFID', '0006_auto_20191104_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='codigo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registro',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
