# Generated by Django 2.2.6 on 2019-11-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroRFID', '0008_remove_registro_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='idalumno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
